### ISSUE TITLE
No node tree specified! Please check the Zeno Scene panel.

### ISSUE THREAD

**Issue by yanzixiang** [zenustech/zenoblend#13]
what does this mean ?

**Comment by hooyuser** [comment]
That means you should select a zeno nodetree first, either a static nodetree or a framed one.

![Zeno Scene](https://user-images.githubusercontent.com/10691820/133721023-8e6c9963-10f2-4106-aa3a-38d4751c7e76.png)

Hopefully we can polish the UI of Zeno nodetree management in the future.

**Comment by yanzixiang** [comment]
![111](https://user-images.githubusercontent.com/33214/133756891-79ed440f-99a1-442a-b7fd-fbde713b8ab6.PNG)

location: <unknown location>:-1
閿欒: Python: Traceback (most recent call last):
  File "C:\Users\yanzixiang\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\zenoblend\execute_operator.py", line 20, in execute
    if not scenario.frame_update_callback():
  File "C:\Users\yanzixiang\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\zenoblend\scenario.py", line 328, in frame_update_callback
    update_scene(static_tree)
  File "C:\Users\yanzixiang\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\zenoblend\scenario.py", line 297, in update_scene
    execute_scene(graph_name, is_framed=False)
  File "C:\Users\yanzixiang\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\zenoblend\scenario.py", line 241, in execute_scene
    core.graphApply(graphPtr)
RuntimeError: ZENO Traceback (most recent call last):
During evaluation of `SubOutput`:
During evaluation of `PrimitiveToMesh`:
invalid primitive attribute name: `tex`

Where is tex ?

**Comment by yanzixiang** [comment]
> Hopefully we can polish the UI of Zeno nodetree management in the future.
I think we can set the first nodetree as default when the user creates it.
Or we can create a default nodetree.

**Comment by hooyuser** [comment]
If you've got the [newest edition](https://github.com/zenustech/zenoblend/releases/tag/2021.9.13), you could try **BlenderOutputPrimitive** node for your purpose.
![example](https://user-images.githubusercontent.com/10691820/133762492-c82d4fb9-d9c8-42dc-85f2-61fdf1a3d1a9.png)
